### ISSUE TITLE
mac设备加了plist文件还是闪退

### ISSUE THREAD

**Issue by LvBisheng** [CoderMJLee/audio-video-dev-tutorial#3]
mac环境（mac os 11.2.4）。下载 09_record_audio_sub_thread的代码 demo，该改的环境变量都改了，在 

    int ret = avformat_open_input(&ctx, DEVICE_NAME, fmt, nullptr);

的地方还是会闪退。希望mj，帮忙解答下。

**Comment by CoderMJLee** [comment]
使用Debug模式运行
